# Generated by Django 5.1.6 on 2025-09-24 21:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import imagekit.models.fields
import inventario.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message="Solo se permiten letras, números, signos de puntuación básicos y caracteres especiales como ', &, /.", regex="^[\\w\\sáéíóúÁÉÍÓÚñÑ\\-.,;:¡!¿?()\\'&/]+$")])),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Solo se permiten letras, números, signos de puntuación básicos y caracteres especiales como ', &, /.", regex="^[\\w\\sáéíóúÁÉÍÓÚñÑ\\-.,;:¡!¿?()\\'&/]+$")])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario_final', models.DecimalField(decimal_places=2, help_text='Precio unitario ajustado proporcionalmente después del descuento', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reembolsado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('motivo', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='El motivo contiene caracteres no permitidos.', regex='^[\\w\\sáéíóúÁÉÍÓÚñÑ\\-.,;:¡!¿?()\\n]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message="Solo se permiten letras, números, signos de puntuación básicos y caracteres especiales como ', &, /.", regex="^[\\w\\sáéíóúÁÉÍÓÚñÑ\\-.,;:¡!¿?()\\'&/]+$")])),
            ],
        ),
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message="Solo se permiten letras, números, signos de puntuación básicos y caracteres especiales como ', &, /.", regex="^[\\w\\sáéíóúÁÉÍÓÚñÑ\\-.,;:¡!¿?()\\'&/]+$")])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoAdministrativo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=1000, validators=[django.core.validators.RegexValidator(message="Solo se permiten letras, números, signos de puntuación básicos y caracteres especiales como ', &, /.", regex="^[\\w\\sáéíóúÁÉÍÓÚñÑ\\-.,;:¡!¿?()\\'&/]+$")])),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Solo se permiten letras, números, signos de puntuación básicos y caracteres especiales como ', &, /.", regex="^[\\w\\sáéíóúÁÉÍÓÚñÑ\\-.,;:¡!¿?()\\'&/]+$")])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('Efectivo dolares', 'Efectivo dolares'), ('Efectivo bolívares', 'Efectivo bolívares'), ('Transferencia', 'Transferencia Bancaria'), ('Pago movil', 'Pago movil'), ('Zelle', 'Zelle'), ('Binance', 'Binance'), ('Saldo', 'Saldo Cliente')], max_length=30, unique=True)),
                ('moneda', models.CharField(choices=[('USD', 'Dólar'), ('VES', 'Bolívar'), ('EUR', 'Euro')], default='USD', max_length=3)),
                ('requiere_tasa', models.BooleanField(default=False, help_text='Indica si este método requiere tasa de cambio')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Solo se permiten letras, números, signos de puntuación básicos y caracteres especiales como ', &, /.", regex="^[\\w\\sáéíóúÁÉÍÓÚñÑ\\-.,;:¡!¿?()\\'&/]+$")])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido.', regex='^\\+?\\d{7,17}$')])),
                ('imagen', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=inventario.models.user_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'heic', 'webp']), inventario.models.validate_image_size])),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Número de intentos fallidos de login')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Fecha y hora hasta cuando el usuario está bloqueado', null=True)),
                ('last_failed_login', models.DateTimeField(blank=True, help_text='Último intento fallido de login', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('can_suspend_user', 'Puede suspender usuarios')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Devolucion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.PositiveIntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('danado', models.BooleanField(default=False, help_text='Indica si el producto va a merma')),
                ('id_detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_devolucion', to='inventario.detalleventa')),
                ('id_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.devolucion')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Solo se permiten letras, números, signos de puntuación básicos y caracteres especiales como ', &, /.", regex="^[\\w\\sáéíóúÁÉÍÓÚñÑ\\-.,;:¡!¿?()\\'&/]+$")])),
                ('apellido', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message="Solo se permiten letras, números, signos de puntuación básicos y caracteres especiales como ', &, /.", regex="^[\\w\\sáéíóúÁÉÍÓÚñÑ\\-.,;:¡!¿?()\\'&/]+$")])),
                ('identificacion', models.IntegerField(unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deuda', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido.', regex='^\\+?\\d{7,17}$')])),
                ('etiqueta', models.ManyToManyField(blank=True, related_name='etiquetas', to='inventario.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El código solo puede contener letras, números, guiones y guiones bajos.', regex='^[A-Za-z0-9\\-_]+$')])),
                ('imagen', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=inventario.models.product_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'heic']), inventario.models.validate_image_size])),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.color')),
                ('fit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.fit')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.marca')),
                ('talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.talla')),
            ],
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('motivo', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='El motivo contiene caracteres no permitidos.', regex='^[\\w\\sáéíóúÁÉÍÓÚñÑ\\-.,;:¡!¿?()\\n]*$')])),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='inventario.producto')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.CreateModel(
            name='TallaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.cliente')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.talla')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='tallas',
            field=models.ManyToManyField(related_name='clientes', through='inventario.TallaCliente', to='inventario.talla'),
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message="Solo se permiten letras, números, signos de puntuación básicos y caracteres especiales como ', &, /.", regex="^[\\w\\sáéíóúÁÉÍÓÚñÑ\\-.,;:¡!¿?()\\'&/]+$")])),
                ('is_active', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.tipo'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_ajustado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado_comision', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('denegado', 'Denegado')], default='pendiente', max_length=10)),
                ('entrega', models.BooleanField(default=False)),
                ('pagado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.cliente')),
                ('productos', models.ManyToManyField(related_name='ventas', through='inventario.DetalleVenta', to='inventario.producto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto_usd', models.DecimalField(decimal_places=2, help_text='Monto en dólares (USD)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_moneda', models.DecimalField(blank=True, decimal_places=2, help_text='Monto en moneda local si aplica', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tasa', models.DecimalField(blank=True, decimal_places=2, help_text='Tasa de cambio al momento del pago (solo para monedas diferentes a USD)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.metodopago')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.venta')),
            ],
        ),
        migrations.AddField(
            model_name='devolucion',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='inventario.venta'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.venta'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), name='codigo_lower_unique'),
        ),
    ]
