# Generated by Django 5.1.6 on 2025-09-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merma',
            name='origen',
            field=models.CharField(choices=[('tienda', 'tienda'), ('devolucion', 'Devolución')], default='tienda', max_length=100),
        ),
    ]
