# Generated by Django 5.1.6 on 2025-09-24 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_merma_origen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detalle_Devolucion',
            new_name='DetalleDevolucion',
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='reembolsado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto reembolsado al cliente', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Total calculado automáticamente', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
