# Generated by Django 5.1.6 on 2025-09-25 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_detalle_devolucion_detalledevolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='deuda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='detalledevolucion',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario_final',
            field=models.DecimalField(decimal_places=6, help_text='Precio unitario ajustado proporcionalmente después del descuento', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='reembolsado',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Monto reembolsado al cliente', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='total',
            field=models.DecimalField(decimal_places=6, help_text='Total calculado automáticamente', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gastoadministrativo',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='merma',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_moneda',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto en moneda local si aplica', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_usd',
            field=models.DecimalField(decimal_places=2, help_text='Monto en dólares (USD)', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tasa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tasa de cambio al momento del pago (solo para monedas diferentes a USD)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_ajustado',
            field=models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
