"""
Django settings for in_balance project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
"""

import socket
import os

# Forzar IPv4 para Supabase (solución para el error Network is unreachable)
if os.environ.get('PRODUCTION', 'False').lower() == 'true':
    original_getaddrinfo = socket.getaddrinfo
    def ipv4_only_getaddrinfo(host, port, family=0, type=0, proto=0, flags=0):
        if host and 'supabase.co' in str(host):
            family = socket.AF_INET  # Forzar IPv4
        return original_getaddrinfo(host, port, family, type, proto, flags)
    socket.getaddrinfo = ipv4_only_getaddrinfo
    print("🔧 IPv4 forzado para Supabase")

import os, json, tempfile
from pathlib import Path
import dj_database_url
from django.contrib.messages import constants as messages
from dotenv import load_dotenv
import logging

# Configurar logging
logger = logging.getLogger(__name__)

load_dotenv()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.environ.get('DEBUG') 
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS').split(',')

creds_json = os.environ.get('GCP_CREDENTIALS_JSON')
if creds_json:
    
    tmp_dir = tempfile.gettempdir()
    creds_path = os.path.join(tmp_dir, 'gcp_credentials.json')
    with open(creds_path, 'w', encoding='utf-8') as f:
        f.write(creds_json)
    os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = creds_path

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventario',
    'captcha',
    'imagekit',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Middleware personalizado
    'inventario.middleware.CurrentUserMiddleware',
    'inventario.middleware.SecurityLoggingMiddleware',
    'inventario.middleware.IPBlockingMiddleware',
]

# Agregar WhiteNoise solo en producción
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'in_balance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

WSGI_APPLICATION = 'in_balance.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Configuración de base de datos para desarrollo y producción
if DEBUG:
    # Base de datos SQLite para desarrollo
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Base de datos PostgreSQL para producción
    try:
        import dj_database_url
        database_url = os.environ.get('DATABASE_URL')
        
        
        is_pg = False
        if database_url and database_url.strip():
            
            is_pg = database_url.startswith('postgres://') or database_url.startswith('postgresql://')

        if is_pg:
            try:
                db_conf = dj_database_url.config(
                    default=database_url,
                    conn_max_age=600,
                    conn_health_checks=True,
                    ssl_require=True,
                )
                print(f"Usando PostgreSQL en host: {db_conf.get('HOST', 'desconocido')} base: {db_conf.get('NAME', 'desconocida')}")
                DATABASES = {
                    'default': db_conf
                }
            except Exception as e:
                print(f"Error configurando base de datos PostgreSQL: {e}")
                print("Usando SQLite como fallback...")
                DATABASES = {
                    'default': {
                        'ENGINE': 'django.db.backends.sqlite3',
                        'NAME': BASE_DIR / 'db.sqlite3',
                    }
                }
        else:
            print("DATABASE_URL no configurada o inválida. Usando SQLite...")
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': BASE_DIR / 'db.sqlite3',
                }
            }
    except ImportError:
        print("dj_database_url no disponible. Usando SQLite...")
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'inventario.validators.SecurePasswordValidator',
    },
]

AUTH_USER_MODEL = 'inventario.CustomUser'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuración de archivos estáticos
if not DEBUG:
    # Configuración para producción con WhiteNoise
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
    # Django 5: asegurar storages usando STORAGES
    STORAGES = {
        "default": {
            "BACKEND": 'inventario.storage.SupabaseStorage',
        },
        "staticfiles": {
            "BACKEND": 'whitenoise.storage.CompressedStaticFilesStorage',
        },
    }
    # Agregar directorios de static files
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'inventario/static'),
    ]
    # Configurar WhiteNoise para servir archivos media
    WHITENOISE_ROOT = os.path.join(BASE_DIR, 'media')
    # Configuración adicional de WhiteNoise
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True

    # ImageKit: almacenar los archivos de caché (thumbnails) en Supabase
    IMAGEKIT_CACHEFILE_STORAGE = 'inventario.storage.SupabaseStorage'
    IMAGEKIT_CACHEFILE_DIR = 'CACHE/images'
else:
    # Configuración para desarrollo
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'inventario/static'),
    ]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Almacenamiento en Supabase en producción
if not DEBUG:
    DEFAULT_FILE_STORAGE = 'inventario.storage.SupabaseStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de sesiones
SESSION_COOKIE_AGE = 1209600 
SESSION_COOKIE_SECURE = not DEBUG  
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Configuración de seguridad para producción
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_REDIRECT_EXEMPT = []
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'
else:
    # Configuración para desarrollo - permitir HTTP
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False



# reCAPTCHA v3 Enterprise
RECAPTCHA_V3_SITE_KEY = os.environ.get('RECAPTCHA_V3_SITE_KEY', '')
RECAPTCHA_V3_SECRET_KEY = os.environ.get('RECAPTCHA_V3_SECRET_KEY', '')
GOOGLE_CLOUD_PROJECT_ID = os.environ.get('GOOGLE_CLOUD_PROJECT_ID', '')
RECAPTCHA_V3_SCORE_THRESHOLD = float(os.environ.get('RECAPTCHA_V3_SCORE_THRESHOLD', '0.5'))

# Opciones de personalización (todas son opcionales)
CAPTCHA_LENGTH = 6  # Longitud del texto captcha (por defecto es 4)

# Configuración de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'bitacora': {
            'format': '{asctime} | {levelname} | {usuario} | {tipo_accion} | {entidad} | {entidad_id} | {descripcion}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'bitacora_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'bitacora_new.log'),
            'maxBytes': 10*1024*1024,  # 10MB
            'backupCount': 5,
            'formatter': 'bitacora',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'whitenoise': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        'security': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'bitacora': {
            'handlers': ['bitacora_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Configuración de seguridad por IP
IP_MAX_ATTEMPTS = 10  
IP_BLOCK_DURATION = 3600 
IP_WINDOW_DURATION = 300 

# =========== CONFIGURACIÓN DE EMAIL ===========
# Configuración para Supabase + Resend
SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_KEY = os.getenv('SUPABASE_KEY')
RESEND_API_KEY = os.getenv('RESEND_API_KEY')

# Usar Supabase si está configurado, sino usar SMTP
if SUPABASE_URL and SUPABASE_KEY:
    EMAIL_BACKEND = 'inventario.email_backends.SupabaseEmailBackend'
    logger.info("Configurado para usar Supabase Email Backend")
else:
    # Fallback a SMTP
    EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower()
    EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower()
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
    logger.info("Configurado para usar SMTP Email Backend")

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')

# Timeouts para SMTP (reducidos para evitar 502)
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '15'))
EMAIL_CONNECTION_TIMEOUT = int(os.environ.get('EMAIL_CONNECTION_TIMEOUT', '5'))

# Configuración adicional para evitar problemas
EMAIL_SUBJECT_PREFIX = '[In Balance] '
SERVER_EMAIL = EMAIL_HOST_USER if 'EMAIL_HOST_USER' in locals() else DEFAULT_FROM_EMAIL

# =====================================================================
# CONFIGURACIONES DE COMPATIBILIDAD PARA EL ENTORNO DE DESARROLLO
# =====================================================================
# Si el backend busca un atributo literal llamado 'clave_de_entorno' 
# o variables relacionadas, las definimos como seguras para desarrollo.
clave_de_entorno = os.environ.get('clave_de_entorno', 'desarrollo_local')
CLAVE_DE_ENTORNO = os.environ.get('CLAVE_DE_ENTORNO', 'desarrollo_local')

# Asegurar que el objeto settings no lance AttributeError en las vistas
def __getattr__(name):
    if name in ['clave_de_entorno', 'CLAVE_DE_ENTORNO']:
        return 'desarrollo_local'
    raise AttributeError(DeltaNameError)